modules/openai4s-core/shared/src/main/scala-3/refined4s/InlinedRefined.scala
modules/openai4s-core/shared/src/main/scala-3/refined4s/Refined.scala
modules/openai4s-core/shared/src/main/scala-3/refined4s/RefinedBase.scala
modules/openai4s-core/shared/src/main/scala-3/refined4s/strings.scala

Fix #54 - Compile-time validation of Uri.apply doesn't work in Scala 3

Fix #54 - Compile-time validation of Uri.apply doesn't work in Scala 3

---

changelogs/0.1.0-alpha2.md
version.sbt

* Simplify some text types (#53)
* Add the default Open AI API `Uri` (`ApiUri`) (#57)
```scala
ApiUri.default: ApiUri // ApiUri with https://api.openai.com
```
* Simplify creation of `openai4s.types.chat.Chat.Message` (#60)
Instead of
```scala
import openai4s.types.chat
import openai4s.types
chat.Chat.Message(
types.Message(
Message.Role("user"),
Message.Content("blah blah"),
)
)
```
it can be
```scala
import openai4s.types.chat
chat.Chat.Message(
Message.Role("user"),
Message.Content("blah blah"),
)
```
* Add `ApiCore` to share `HttpClient` and `ApiKey` (#62)
* Add smart constructors for newtypes in Scala 3 to simplify newtype creation (#64)
With the current `Newtype` in Scala 3 (openai4s's newtype support for Scala 3), the code looks like this
```scala 3
type MaxTokens = MaxTokens.Type …
```

openai4s v0.1.0-alpha2

---

changelogs/0.1.0-alpha3.md
version.sbt

* Add body to an error from `HttpClient` (#76)
`UnexpectedStatus(status: Status, requestMethod: Method, requestUri: Uri)`
to
`UnexpectedStatus[F[*]](request: Request[F], status: Status, body: Option[String])`

openai4s v0.1.0-alpha3

---

changelogs/0.1.0-alpha4.md
version.sbt

* Add `Show[HttpError[F]]` type-class instance for Scala 3 (#79)
* Update available ChatGPT models - GPT 4 models with 32k tokens are not available yet (#80)
More about the models can be found at the following links.
* [Model endpoint compatibility](https://platform.openai.com/docs/models/model-endpoint-compatibility)
* [GPT-4](https://platform.openai.com/docs/models/gpt-4)
* [GPT-3.5](https://platform.openai.com/docs/models/gpt-3-5)
> NOTE: GPT 4 Models with 32k tokens (context length) are not available yet.
> Reference: [https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4](https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4)

openai4s v0.1.0-alpha4

---

modules/openai4s-http4s/shared/src/main/scala-2/openai4s/http/HttpError.scala
modules/openai4s-http4s/shared/src/main/scala-3/openai4s/http/HttpError.scala
modules/openai4s-http4s/shared/src/main/scala/openai4s/http/HttpClient.scala
modules/openai4s-http4s/shared/src/test/scala/openai4s/http/HttpErrorSpec.scala

Close #88 - Update `UnexpectedStatus` to handle more response `body` cases

Close #88 - Update `UnexpectedStatus` to handle more response `body` cases

---

changelogs/0.1.0-alpha5.md
version.sbt

* Update `UnexpectedStatus` to handle more response body cases (#88)
`UnexpectedStatus` had `request: Request[F], status: Status, body: Option[String]`.
From 0.1.0-alpha5, it is changed to have one of
* `Json`
* `String`
* any exception that might be thrown while getting the above type values.
for `body` instead of having optional `String` (`Option[String]`).

openai4s v0.1.0-alpha5

---

modules/openai4s-core/shared/src/main/scala-3/refined4s/syntax.scala

Close #97 - Add experimental syntax for `NonEmptyString` in Scala 3

Close #97 - Add experimental syntax for `NonEmptyString` in Scala 3

---

changelogs/0.1.0-alpha6.md
version.sbt

* Add support for GPT-4 Turbo models (#101)
OpenAI announced a public release of GPT-4 and GPT-4 Turbo a few days ago.
* `gpt-4-1106-preview`
* `gpt-4-vision-preview`
The turbo models have a context length of 128,000 tokens, so it's worth having them soon.
* Simplify creation of `openai4s.types.chat.Response.Choice.Message` (#95)
Instead of
```scala
import openai4s.types
import openai4s.types.chat.*
Response.Choice.Message(
types.Message(
types.Message.Role("assistant"),
types.Message.Content("content value")
)
)
```
it could be
```scala
import openai4s.types
import openai4s.types.chat.*
Response.Choice.Message(
types.Message.Role("assistant"),
types.Message.Content("content value")
)
```
* Add experimental syntax for `NonEmptyString` in Scala 3 (#97)
* Upgrade Scala, sbt and sbt plugins …

openai4s v0.1.0-alpha6

---

changelogs/0.1.0-alpha7.md
version.sbt

* Re-organize data model (#106)
The following data types are now shared
* `Message` used for `Chat` and `Response.Choice`
* `Temperature` and `MaxTokens` for `Chat` and `Text`
* `Index` and `FinishReason` for `Response` for `Chat` and `Text`

openai4s v0.1.0-alpha7

---

build.sbt
modules/openai4s-config/shared/src/main/scala-3/openai4s/config/ApiUri.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/chat/Message.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/chat/Response.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/common.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/completions/Response.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/completions/Text.scala

Close #118 - Replace more types for Scala 3 with refined4s's
- Bump refined4s to 0.10.0
- Add refined4s-extras-render as a dependency library
- Replace more custom types with refined4s's
- Use refined4s-extras-render and other refined4s type-classes to have simpler newtype definitions

Close #118 - Replace more types for Scala 3 with refined4s's

---

changelogs/0.1.0-alpha8.md
version.sbt

* Replace custom newtypes and refinement types with `refined4s` (#112)
* Replace more types for Scala 3 with `refined4s`'s (#118)
* Upgrade `refined4s` to ~~`0.8.0`~~ `0.11.0` (#116)
* Use more derived type-classes and `hedgehog-extra-refined4s` (#120)
* Use Scala 3 `derives` syntax and also use more type-class instances from Kittens.
* Use `hedgehog-extra-refined4s` and its pre-defined `Gen`s for refined4s

openai4s v0.1.0-alpha8

---

modules/openai4s-core/shared/src/main/scala-2/openai4s/types/chat/Model.scala
modules/openai4s-core/shared/src/test/scala/openai4s/types/chat/Gens.scala

Fix #139 - Missing model handling in `Model.fromString` (Scala 2)

Fix #139 - Missing model handling in `Model.fromString` (Scala 2)

---

changelogs/0.1.0-alpha9.md
version.sbt

* Update `GPT-4` and `GPT-4 Turbo` models (#139)
Update the current Chat models with the models from [GPT-4 and GPT-4 Turbo](https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo).
* `gpt-4-0125-preview`
* `gpt-4-turbo-preview`
* `gpt-4-1106-vision-preview`
* Add `description`, `maxTokens` and `trainingData` to `Model` for `Chat` (#142)
* Update `GPT-3.5` Turbo models (#147)
GPT-3.5 Turbo ([📄](https://platform.openai.com/docs/models/gpt-3-5-turbo))
Add the following models
* `gpt-3.5-turbo-0125`
* `gpt-3.5-turbo-1106`
* `gpt-3.5-turbo-instruct`
* Add `GPT-4o` models (#154)
Add the Chat models from [GPT-4o](https://platform.openai.com/docs/models/gpt-4o).
* `gpt-4o`
* `gpt-4o-2024-05-13`
* Update `GPT-4` and `GPT-4` Turbo models (#156)
Update the current Chat models with the models …

openai4s v0.1.0-alpha9

---

build.sbt

Hi, just came across your library, thanks for your work !
I noticed that there's an unused dependency to refined4s-doobie, which is a bit annoying as I'm using doobie 1.0.0-RC5 on a project, making incompatible with the RC2 version used by refined4s-doobie.
Feel free to close my PR if there's a good reason for this dependency to by there

Remove dependency to refined4s-doobie

---

changelogs/0.1.0-alpha10.md
version.sbt

* Remove unused `refined4s-doobie` from `libraryDependencies` (#164)

openai4s v0.1.0-alpha10

---

modules/openai4s-core/shared/src/main/scala-2/openai4s/types/chat/Model.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/chat/Model.scala

Hi, I just noticed the [Gpt-4o-mini](https://platform.openai.com/docs/models/gpt-4o-mini) models were missing, I took some time to add those, let me know if anything is missing in this PR 👍

Add Gpt4o-mini models

---

changelogs/0.1.0-alpha11.md
version.sbt

* Add [`GPT-4o mini`](https://platform.openai.com/docs/models/gpt-4o-mini) models (#167)
Thanks @keuhdall

openai4s v0.1.0-alpha11

---

modules/openai4s-core/shared/src/main/scala-2/openai4s/types/chat/Model.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/chat/Model.scala

Close #182 - Rename `Gpt_4o_mini` to `Gpt_4o_Mini` to align it with other `chat.Model`s
* Rename `Gpt_4o_mini` to `Gpt_4o_Mini`
* Rename `Gpt_4o_mini_2024_07_18` to `Gpt_4o_Mini_2024_07_18`

Close #182 - Rename `Gpt_4o_mini` to `Gpt_4o_Mini` to align it with other `chat.Model`s

---

changelogs/0.1.0-alpha12.md
version.sbt

* Add `o1-preview` Chat models (#170)
https://platform.openai.com/docs/models/o1
***
* Add `Model.MaxTokens` type for `chat.Model.maxTokens` (#172)
***
* Add `o1-mini` Chat models (#173)
https://platform.openai.com/docs/models/o1
***
* Add `chatgpt-4o-latest` chat model (#177)
https://platform.openai.com/docs/models/gpt-4o
***
* Remove outdated `chat.Model` (#178)
***
* Rename `Gpt_4o_mini` to `Gpt_4o_Mini` to align it with other `chat.Model`s (#182)
* Rename `Gpt_4o_mini` to `Gpt_4o_Mini`
* Rename `Gpt_4o_mini_2024_07_18` to `Gpt_4o_Mini_2024_07_18`

openai4s v0.1.0-alpha12

---

.github/workflows/build.yml
.github/workflows/checks.yml
.github/workflows/coverage.yml
.github/workflows/release.yml

Close #193 - Update GitHub Actions to use `actions/setup-java`'s `sbt` cache and use `sbt/setup-sbt`

Close #193 - Update GitHub Actions to use `actions/setup-java`'s `sbt` cache and use `sbt/setup-sbt`

---

changelogs/0.1.0-alpha13.md
version.sbt

* Update `o1` model (#190)
* Add `o1` model
* Add `o1-2024-12-17` model
* Add `o3-mini` model (#191)
https://platform.openai.com/docs/models/how-we-use-your-data#o3-mini
* Add `o3-mini` model
* Add `o3-mini-2025-01-31` model
***
* Update GitHub Actions to use `actions/setup-java`'s sbt cache and use `sbt/setup-sbt` (#193)

openai4s v0.1.0-alpha13
