kevin-lee/openai4s

codecov.yml

Add: `codecov.yml` with `layout` and `behavior` settings

Add: `codecov.yml` with `layout` and `behavior` settings

---

modules/openai4s-config/shared/src/main/scala-2/openai4s/config/ApiUri.scala
modules/openai4s-config/shared/src/main/scala-2/openai4s/config/OpenAiConfig.scala
modules/openai4s-config/shared/src/main/scala-3/openai4s/config/ApiUri.scala
modules/openai4s-config/shared/src/main/scala-3/openai4s/config/OpenAiConfig.scala
modules/openai4s-config/shared/src/main/scala/openai4s/config/CommonConstants.scala

Close #57 - Add the default Open AI API `Uri` (`ApiUri`)

Close #57 - Add the default Open AI API Uri (ApiUri)

---

modules/openai4s-core/shared/src/main/scala-2/openai4s/types/Message.scala
modules/openai4s-core/shared/src/main/scala-2/openai4s/types/chat/Chat.scala
modules/openai4s-core/shared/src/main/scala-2/openai4s/types/completions/Text.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/Message.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/completions/Text.scala
modules/openai4s-core/shared/src/test/scala/openai4s/types/Gens.scala
modules/openai4s-core/shared/src/test/scala/openai4s/types/completions/Gens.scala

Close #53 - Simplify some text types

Close #53 - Simplify some text types

---

modules/openai4s-core/shared/src/main/scala-2/openai4s/types/chat/Chat.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/chat/Chat.scala
modules/openai4s-core/shared/src/test/scala/openai4s/types/chat/ChatSpec.scala

Close #60 - Simplify creation of `openai4s.types.chat.Chat.Message`

Close #60 - Simplify creation of `openai4s.types.chat.Chat.Message`

---

modules/openai4s-api/shared/src/main/scala/openai4s/api/ApiCore.scala
modules/openai4s-api/shared/src/main/scala/openai4s/api/chat/ChatApi.scala
modules/openai4s-api/shared/src/main/scala/openai4s/api/completions/CompletionsApi.scala
modules/openai4s-api/shared/src/test/scala/openai4s/api/chat/ChatApiSpec.scala
modules/openai4s-api/shared/src/test/scala/openai4s/api/completions/CompletionsApiSpec.scala

Close #62 - Add `ApiCore` to share `HttpClient` and `ApiKey`

Close #62 - Add `ApiCore` to share `HttpClient` and `ApiKey`

---

modules/openai4s-core/shared/src/main/scala-2/openai4s/types/chat/Response.scala
modules/openai4s-core/shared/src/main/scala-3/newtype4s/Newtype.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/chat/Chat.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/chat/Response.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/completions/Text.scala
modules/openai4s-core/shared/src/main/scala-3/refined4s/numeric.scala
modules/openai4s-core/shared/src/test/scala-3/openai4s/compat/TypesCompat.scala
modules/openai4s-core/shared/src/test/scala/openai4s/types/chat/Gens.scala
modules/openai4s-core/shared/src/test/scala/openai4s/types/chat/ResponseSpec.scala

Close #64 - Add smart constructors for newtypes in Scala 3 to simplify newtype creation

Close #64 - Add smart constructors for newtypes in Scala 3 to simplify newtype creation

---

project/build.properties

Upgrade: sbt to `1.9.3`

---

version.sbt

Update: `version.sbt` reset to `0.1.0-SNAPSHOT`

Update: `version.sbt` reset to `0.1.0-SNAPSHOT`

---

build.sbt

Upgrade cats to `2.10.0` / http4s to `0.23.23`

Upgrade cats to 2.10.0 / http4s to 0.23.23

---

.github/workflows/release.yml
changelogs/0.1.0-alpha1.md

Update: GitHub Actions config - remove uploading artifacts to GitHub Release
- Also fix the incorrect release date of `0.1.0-alpha1`

Update: GitHub Actions config - remove uploading artifacts to GitHub Release

---

README.md

Update: `README.md` - Add example code

Update: `README.md` - Add example code

---

version.sbt

Update: `version.sbt` - reset to `0.1.0-SNAPSHOT`

Update: `version.sbt` - reset to `0.1.0-SNAPSHOT`

---

modules/openai4s-http4s/shared/src/main/scala-2/openai4s/http/HttpError.scala
modules/openai4s-http4s/shared/src/main/scala/openai4s/http/HttpClient.scala

Close #76 - Add body to an error from `HttpClient`

Close #76 - Add body to an error from `HttpClient`

---

modules/openai4s-http4s/shared/src/main/scala-3/openai4s/http/HttpError.scala
modules/openai4s-http4s/shared/src/test/scala/openai4s/http/HttpErrorSpec.scala

Close #79 - Add `Show[HttpError[F]]` type-class instance for Scala 3

Close #79 - Add `Show[HttpError[F]]` type-class instance for Scala 3

---

modules/openai4s-core/shared/src/main/scala-2/openai4s/types/chat/Model.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/chat/Model.scala
modules/openai4s-core/shared/src/test/scala/openai4s/types/chat/Gens.scala

Close #80 - Update available ChatGPT models - GPT 4 models with 32k tokens are not available yet

Close #80 - Update available ChatGPT models - GPT 4 models with 32k tokens are not available yet

---

version.sbt

Update: version.sbt - reset to 0.1.0-SNAPSHOT

Update: version.sbt - reset to 0.1.0-SNAPSHOT

---

project/build.properties

Upgrade sbt to `1.9.4`

---

build.sbt

Bump extras and logback
- extras to `0.42.0`
- logback to `1.4.11`

Bump extras and logback

---

modules/openai4s-core/shared/src/main/scala-2/openai4s/types/chat/Response.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/chat/Response.scala

Close #95 - Simplify creation of `openai4s.types.chat.Response.Choice.Message`

Close #95 - Simplify creation of `openai4s.types.chat.Response.Choice.Message`

---

modules/openai4s-core/shared/src/main/scala-2/openai4s/types/chat/Model.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/chat/Model.scala
modules/openai4s-core/shared/src/test/scala/openai4s/types/chat/Gens.scala
modules/openai4s-core/shared/src/test/scala/openai4s/types/chat/ModelSpec.scala

Close #101 - Add support for GPT-4 Turbo models

Close #101 - Add support for GPT-4 Turbo models

---

.github/workflows/build.yml
.github/workflows/checks.yml
.github/workflows/release.yml
.github/workflows/sbt-build-all.sh
build.sbt
modules/openai4s-core/shared/src/main/scala-3/newtype4s/Newtype.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/Message.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/completions/Response.scala
modules/openai4s-core/shared/src/main/scala-3/refined4s/strings.scala
modules/openai4s-core/shared/src/test/scala/openai4s/types/chat/ResponseSpec.scala
modules/openai4s-http4s/shared/src/main/scala/openai4s/http/HttpClient.scala
modules/openai4s-http4s/shared/src/test/scala/openai4s/http/HttpClientStub.scala
project/build.properties
project/plugins.sbt

Close #103 - Upgrade Scala, sbt and sbt plugins
- Scala 2 to 2.13.12
- Scala 3 to 3.3.1
- sbt to 1.9.7
- sbt-wartremover to 3.1.5
- sbt-tpolecat to 0.5.0
- sbt-scalafix to 0.11.1
- sbt-scalafmt to 2.5.2
- sbt-scoverage to 2.0.9
- sbt-mdoc to 2.5.1

Close #103 - Upgrade Scala, sbt and sbt plugins

---

modules/openai4s-core/shared/src/main/scala-2/openai4s/types/chat/Chat.scala
modules/openai4s-core/shared/src/main/scala-2/openai4s/types/chat/Message.scala
modules/openai4s-core/shared/src/main/scala-2/openai4s/types/chat/Response.scala
modules/openai4s-core/shared/src/main/scala-2/openai4s/types/common.scala
modules/openai4s-core/shared/src/main/scala-2/openai4s/types/completions/Response.scala
modules/openai4s-core/shared/src/main/scala-2/openai4s/types/completions/Text.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/chat/Chat.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/chat/Message.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/chat/Response.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/common.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/completions/Response.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/completions/Text.scala
modules/openai4s-core/shared/src/test/scala-2/openai4s/compat/TypesCompat.scala
modules/openai4s-core/shared/src/test/scala/openai4s/types/Gens.scala
modules/openai4s-core/shared/src/test/scala/openai4s/types/chat/ChatSpec.scala
modules/openai4s-core/shared/src/test/scala/openai4s/types/chat/Gens.scala
modules/openai4s-core/shared/src/test/scala/openai4s/types/chat/ResponseSpec.scala
modules/openai4s-core/shared/src/test/scala/openai4s/types/completions/Gens.scala
modules/openai4s-core/shared/src/test/scala/openai4s/types/completions/ResponseSpec.scala

Close #106 - Re-organize data model

Close #106 - Re-organize data model

---

README.md

Update: `README.md` - with the latest version

Update: `README.md` - with the latest version

---

build.sbt
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/chat/Response.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/common.scala

Bump refined4s to 0.7.0

---

build.sbt

Close #116 - Upgrade `refined4s` to `0.8.0`

Close #116 - Upgrade `refined4s` to `0.8.0`

---

build.sbt
modules/openai4s-core/shared/src/main/scala-2/openai4s/types/chat/Chat.scala
modules/openai4s-core/shared/src/main/scala-2/openai4s/types/chat/Message.scala
modules/openai4s-core/shared/src/main/scala-2/openai4s/types/chat/Response.scala
modules/openai4s-core/shared/src/main/scala-2/openai4s/types/common.scala
modules/openai4s-core/shared/src/main/scala-2/openai4s/types/completions/Response.scala
modules/openai4s-core/shared/src/main/scala-2/openai4s/types/completions/Text.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/completions/Response.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/completions/Text.scala
modules/openai4s-core/shared/src/test/scala-2/openai4s/compat/TypesCompat.scala
modules/openai4s-core/shared/src/test/scala-3/openai4s/compat/TypesCompat.scala
modules/openai4s-core/shared/src/test/scala/openai4s/types/chat/Gens.scala
modules/openai4s-core/shared/src/test/scala/openai4s/types/chat/ModelSpec.scala

Close #120 - Use more derived type-classes and `hedgehog-extra-refined4s`

Close #120 - Use more derived type-classes and `hedgehog-extra-refined4s`

---

README.md

Update: `README.md` - with the latest version info

Update: `README.md` - with the latest version info

---

build.sbt
modules/openai4s-config/shared/src/main/scala-2/openai4s/config/ApiKey.scala
modules/openai4s-config/shared/src/main/scala-2/openai4s/config/ApiUri.scala
modules/openai4s-config/shared/src/main/scala-2/openai4s/config/CommonConstants.scala
modules/openai4s-config/shared/src/main/scala-2/openai4s/config/OpenAiConfig.scala
modules/openai4s-core/shared/src/main/scala-2/openai4s/types/chat/Model.scala
modules/openai4s-core/shared/src/main/scala-2/openai4s/types/chat/Response.scala
modules/openai4s-core/shared/src/main/scala-2/openai4s/types/common.scala
modules/openai4s-core/shared/src/main/scala-2/openai4s/types/completions/Model.scala
modules/openai4s-core/shared/src/main/scala-2/openai4s/types/completions/Response.scala
modules/openai4s-core/shared/src/main/scala-2/openai4s/types/completions/Text.scala
modules/openai4s-core/shared/src/test/scala-2/openai4s/compat/TypesCompat.scala
modules/openai4s-core/shared/src/test/scala-3/openai4s/compat/TypesCompat.scala

Close #125 - Use `refined4s-refined-compat` modules

Close #125 - Use `refined4s-refined-compat` modules

---

build.sbt

Close #130 - Bump `hedgehog-extra` to `0.7.0`

Close #130 - Bump `hedgehog-extra` to `0.7.0`

---

build.sbt
project/plugins.sbt

Bump sbt plugins
- sbt-devoops to 3.0.0
- sbt-docusaur to 0.15.0 and fix the config as the new sbt-devoops requires

Bump sbt plugins

---

project/plugins.sbt

Bump sbt-devoops to 3.1.0 and sbt-docusaur to 0.16.0

Bump sbt-devoops to 3.1.0 and sbt-docusaur to 0.16.0

---

modules/openai4s-core/shared/src/main/scala-2/openai4s/types/chat/Model.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/chat/Model.scala

Close #139 - Update GPT-4 and GPT-4 Turbo models

Close #139 - Update GPT-4 and GPT-4 Turbo models

---

modules/openai4s-core/shared/src/main/scala-2/openai4s/types/chat/Model.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/chat/Model.scala

Close #141 - Remove deprecated models

Close #141 - Remove deprecated models

---

modules/openai4s-core/shared/src/main/scala-2/openai4s/types/chat/Model.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/chat/Model.scala

Close #142 - Add `description`, `maxTokens` and `trainingData` to `Model` for `Chat`

Close #142 - Add `description`, `maxTokens` and `trainingData` to `Model` for `Chat`

---

modules/openai4s-core/shared/src/main/scala-2/openai4s/types/chat/Model.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/chat/Model.scala

Close #147 - Update GPT-3.5 Turbo models

Close #147 - Update GPT-3.5 Turbo models

---

build.sbt

Close #150 - Bump `refined4s` to `0.15.0`

Close #150 - Bump `refined4s` to `0.15.0`

---

.github/workflows/build.yml

Update GitHub Actions config for Codecov - add `CODECOV_TOKEN` info

Update GitHub Actions config for Codecov - add `CODECOV_TOKEN` info

---

.github/workflows/coverage.yml
.github/workflows/release.yml

GitHubActions: Add separate test coverage build (`coverage.yml`) with Codecov

GitHubActions: Add separate test coverage build (`coverage.yml`) with Codecov

---

modules/openai4s-core/shared/src/main/scala-2/openai4s/types/chat/Model.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/chat/Model.scala

Close #154 - Add `GPT-4o` models

Close #154 - Add `GPT-4o` models

---

modules/openai4s-core/shared/src/main/scala-2/openai4s/types/chat/Model.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/chat/Model.scala

Close #156 - Update `GPT-4` Turbo models

Close #156 - Update `GPT-4` Turbo models

---

README.md

Update `README.md` - with the latest version info

Update `README.md` - with the latest version info

---

modules/openai4s-core/shared/src/main/scala-2/openai4s/types/chat/Model.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/chat/Model.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/common.scala

Minor changes - Remove unnecessary newline and add comments

Minor changes - Remove unnecessary newline and add comments

---

modules/openai4s-core/shared/src/main/scala-2/openai4s/types/chat/Model.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/chat/Model.scala

Close #170 - Add `o1-preview` Chat models

Close #170 - Add `o1-preview` Chat models

---

modules/openai4s-core/shared/src/main/scala-2/openai4s/types/chat/Model.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/chat/Model.scala

Close #173 - Add `o1-mini` Chat models

Close #173 - Add `o1-mini` Chat models

---

modules/openai4s-core/shared/src/main/scala-2/openai4s/types/chat/Model.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/chat/Model.scala

Close #172 - Add `Model.MaxTokens` type for `chat.Model.maxTokens`

Close #172 - Add `Model.MaxTokens` type for `chat.Model.maxTokens`

---

modules/openai4s-core/shared/src/main/scala-2/openai4s/types/chat/Model.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/chat/Model.scala

Close #178 - Remove outdated `chat.Model`

Close #178 - Remove outdated `chat.Model`

---

modules/openai4s-core/shared/src/main/scala-2/openai4s/types/chat/Model.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/chat/Model.scala

Close #171 - Add Max output tokens (`maxOutputTokens`) to Chat models

Close #171 - Add Max output tokens (`maxOutputTokens`) to Chat models

---

modules/openai4s-core/shared/src/main/scala-2/openai4s/types/chat/Model.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/chat/Model.scala

Close #177 - Add `chatgpt-4o-latest` chat model

Close #177 - Add `chatgpt-4o-latest` chat model

---

modules/openai4s-core/shared/src/main/scala-2/openai4s/types/chat/Model.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/chat/Model.scala

Close #190 - Update `o1` model

Close #190 - Update `o1` model

---

modules/openai4s-core/shared/src/main/scala-2/openai4s/types/chat/Model.scala
modules/openai4s-core/shared/src/main/scala-3/openai4s/types/chat/Model.scala

Close #191 - Add `o3-mini` model

Close #191 - Add `o3-mini` model

---

project/build.properties

Update: `build.properties` - bump sbt to `1.10.11`

Update: `build.properties` - bump sbt to `1.10.11`
